### ISSUE TITLE
Request: [Button] and [ShowNativeProperty]

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#17]
SaintsField being a fork of Naughty it is better if it keeps the same attributes and add new ones.

![image](https://github.com/TylerTemp/SaintsField/assets/26075468/ea801cc6-024b-4d64-a630-42ae3eb0f0c6)
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/9c7bea01-05ed-4838-a5aa-5040762801fe)

**Comment by TylerTemp** [comment]
Hi, thanks for reporting.

Though it's a good advice, it'll have too many problems to keep API level compatible with NaughtyAttributes.

Here is a piece of document of migrate from NaughtyAttributes. (Well, this will be merged to the document when I have spare time)

## Editor Level Component ##

NA needs Editor component to render [meta attributes](https://github.com/dbrizov/NaughtyAttributes?tab=readme-ov-file#meta-attributes) (Like `Button`, `GroupBox`, `ShowIf`). It's applied by default. Once it's installed, it can not be removed unless changing the source code.

SaintsField also needs Editor component to render [`SaintsEditor` attributes](https://github.com/TylerTemp/SaintsField/?tab=readme-ov-file#saintseditor). You need to go `Window` - `Saints` - `Apply SaintsEditor` to enable it. This ensure that SaintsField won't break your project when you only want to use "pure attributes"

![Saints Menu](https://github.com/TylerTemp/SaintsField/assets/6391063/272e72c3-656c-47e4-adc6-75ba62f7f432)

The namespace is `SaintsField.Playa`, to difference between "pure attributes" with "editor attributes"

## Button ##

It's under namespace `SaintsField.Playa`

```csharp
using SaintsField.Playa;  // add this line please

[Button]
private void MethodOne() { }

[Button("Button Text")]
private void MethodTwo() { }
```

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/5e6004c9-b1dd-41a8-8322-6e2d502f4d09)

To enable/disable in different mode:

```csharp
// naughtyattributes uses EButtonEnableMode
[Button("Button Text", EButtonEnableMode.Editor)]
private void MethodTwo() { }

// SaintsEditor uses PlayaDisableIf
[Button("Button Text"), PlayaDisableIf(EMode.Edit)]
private void MethodTwo() { }
```

Difference: NaughtyAttributes allow `IEnumerable`, which is not supported by `SaintsEditor`.

## Show Non-Serializable Fields/Attributes ##

In NaughtyAttributes we have `ShowNativeProperty` (for non-serializable property) and `ShowNonSerializedField` (for non-serializable fields).

In `SaintsEditor` it's `ShowInInspector`, because I really don't care it's a property or a field.

```csharp
using SaintsField.Playa;  // add this line please

[ShowInInspector]
public static Color MyStaticProp => Color.green;  // native Property

[ShowInInspector]
public static Color StaticField = Color.blue;  // non serialized Property

[ShowInInspector]
public static readonly string StaticReadOnlyField = "Building Nothing Out of Something";  // non serialized Field

[ShowInInspector]
public const float MyConst = 3.14f;  // non serialized Field
```

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/688ca956-f6c0-4205-8f86-7fdd26924418)

## Other Difference ##

Will be updated to document someday (like, `Label` is `RichLabel`)

**Comment by laurentopia** [comment]
Oh I didn't know there was a 1:1 equivalent. I wonder where I was looking :/
