### ISSUE TITLE
Any way to colour the name of a list?

### ISSUE THREAD

**Issue by TheEmbracedOne** [TylerTemp/SaintsField#18]
First and foremost, thank you for this amazing tool! I'm currently using it along NaughtyAttributes.
I'd like to colour the name of the list. As I understand that currently, this colours only the elements in a list:
```cs
[RichLabel("<color=#f54e42><label/>")] public List<MapDestination> destinationsAccessibleFromHere;
```
![image](https://github.com/TylerTemp/SaintsField/assets/16197906/a2f1387f-3d5b-4df0-ab8a-b14c8abd7fa9)
but I'd like to colour the name of the list instead. I am using this colouring to colour code variables on prefabs that need to be filled in once the prefabs are placed and it'd be helpful if there was a way to colour the name of the list instead of its elements.

Thank you

**Comment by TylerTemp** [comment]
At the moment it can not. But [it's already in plan](https://github.com/TylerTemp/SaintsField/issues/15) #15

**Comment by TylerTemp** [comment]
Hi, since 2.3.9, it can be done with `PlayaRichLabel ` (but it requires `SaintsEditor`)

There is some issue changing label for `SaintsArray`, `SaintsList`. Will be fixed on next release.

**Comment by TylerTemp** [comment]
Hi, since 2.4.2, there are several ways to do it.

**Option 1**

Enable `SaintsEditor`. This is the most "correct" way, but you'll no longer be able to use meta attributes from NaughtyAttributes

```charp
[PlayaRichLabel("<color=lame>It's Labeled!")]
public List<string> myList;

[PlayaRichLabel(nameof(MethodLabel), true)]
public string[] myArray;

// ReSharper disable once ParameterTypeCanBeEnumerable.Local
private string MethodLabel(string[] values)
{
    return $"<color=green><label /> {string.Join("", values.Select(_ => "<icon=star.png />"))}";
}
```

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/80f28645-b2c5-482a-9d33-67e730239451)

**Option 2**

Using `SaintsArray`/`SaintsList`, this is a struct wrapped array/list. Not recommended.

```csharp
[RichLabel("<color=cyan><label /><icon=star.png />"), SaintsArray]
public SaintsList<GameObject> saintsListGo;
```

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/afb4c6af-ef84-4d37-bea4-a96b0bdb02a3)

Because of the limitations of Unity, there does not have some better ways I can think of.

----------------------------------------

I'll close this issue as it's been implemented. If you had any issue using these, please open a new issue. If you have other ideas, please either open a new issue or comment on this one (and I'll open it again)
