### ISSUE TITLE
Visual mess when using SaintsField's ReadOnly 

### ISSUE THREAD

**Issue by MJRamon** [TylerTemp/SaintsField#2]
Label and value fields are messed up when using SaintsField's ReadOnly attribute:
![image](https://github.com/TylerTemp/SaintsField/assets/2642227/afdcb52e-4f00-4174-a10f-7d807fb0e302)

```
        [ReadOnly, SerializeField] private float _currentForwardSpeedInUnits;
        [ReadOnly, SerializeField] private float _currentSpeedInUnits;
        [ReadOnly, SerializeField] private float _currentSpeedInKmph;
        [ReadOnly, SerializeField] private float _maxSpeedKmph;
```

Not using ReadOnly attribute:
![image](https://github.com/TylerTemp/SaintsField/assets/2642227/df6f9c6b-b551-4250-9bea-859d4b24bd9b)

```
        [SerializeField] private float _currentForwardSpeedInUnits;
        [SerializeField] private float _currentSpeedInUnits;
        [SerializeField] private float _currentSpeedInKmph;
        [SerializeField] private float _maxSpeedKmph;
```

**Comment by MJRamon** [comment]
Custom solution works fine:

```
public class ReadOnlyAttribute : PropertyAttribute { }
```

```
    [CustomPropertyDrawer(typeof(ReadOnlyAttribute))]
    public class ReadOnlyDrawer : PropertyDrawer {
        public override float GetPropertyHeight(SerializedProperty property, GUIContent label) {
            return EditorGUI.GetPropertyHeight(property, label, true);
        }

        public override void OnGUI(Rect position, SerializedProperty property, GUIContent label) {
            var previousGUIState = GUI.enabled;
            GUI.enabled = false;
            EditorGUI.PropertyField(position, property, label, true);
            GUI.enabled = previousGUIState;
        }
    }
```

**Comment by TylerTemp** [comment]
Hi, cloud you please provide a reproducible script/project? I at this point can not reproducible this issue:

```csharp
public class Issue2 : MonoBehaviour
{
    public bool enableVisualDebug;

    [SepTitle("Separate Here", EColor.Black)]
    [ReadOnly, SerializeField] private float _currentForwardSpeedInUnits;
    [ReadOnly, SerializeField] private float _currentSpeedInUnits;
    [ReadOnly, SerializeField] private float _currentSpeedInKmph;
    [ReadOnly, SerializeField] private float _maxSpeedKmph;

    public int throttle;
    public int currentGear;
}
```

IU Toolkit: 

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/4f587d61-a1b7-4f07-99c9-c5986f4af652)


IMGUI (Oh there is a bug in IMGUI 😔 but not related to this issue):

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/aecb6169-a560-4d08-a268-1e2a61e0e915)

Unity: 2022.2.0f1

--------------------------------------------------------

P.S. The `readonly` and `showIf/hideIf` indeed need some re-work that I'll do recent days. This is most likely because the `EditorGUI.EndDisabledGroup();` failed to execute in pair with `EditorGUI.StartDisabledGroup();` in SaintsField. So if you can give more detail it'll be appreciated.

**Comment by TylerTemp** [comment]
Hi, cloud you please provide a reproducible script/project? I at this point can not reproducible this issue:

```csharp
public class Issue2 : MonoBehaviour
{
    public bool enableVisualDebug;

    [SepTitle("Separate Here", EColor.Black)]
    [ReadOnly, SerializeField] private float _currentForwardSpeedInUnits;
    [ReadOnly, SerializeField] private float _currentSpeedInUnits;
    [ReadOnly, SerializeField] private float _currentSpeedInKmph;
    [ReadOnly, SerializeField] private float _maxSpeedKmph;

    public int throttle;
    public int currentGear;
}
```

IU Toolkit: 

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/4f587d61-a1b7-4f07-99c9-c5986f4af652)


IMGUI (Oh there is a bug in IMGUI 😔 but not related to this issue):

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/aecb6169-a560-4d08-a268-1e2a61e0e915)

Unity: 2022.2.0f1

--------------------------------------------------------

P.S. The `readonly` and `showIf/hideIf` indeed need some re-work that I'll do recent days. This is most likely because the `EditorGUI.EndDisabledGroup();` failed to execute in pair with `EditorGUI.StartDisabledGroup();` in SaintsField. So if you can give more detail it'll be appreciated.

**Comment by TylerTemp** [comment]
Closed due to can't reproduce + lack of activity.

Please comment on this issue or open another issue if you still face this(or similar) problem.
