### ISSUE TITLE
[GetComponentInChildren] doesn't work for List

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#47]
repro:
add the component with this
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/54152126-8105-4d40-b2d0-ec1fcd5fc835)
= nothing happens and the list is still empty
expected: list populated by all the things derived from that type.

**Comment by TylerTemp** [comment]
Hi,

this is related to [#45](https://github.com/TylerTemp/SaintsField/issues/45), which affects `GetComponent`, `GetComponentInParent(s)`, `GetPrefabtWithComponent` etc. and is working in process

**Comment by laurentopia** [comment]
gotcha, thanks!

**Comment by TylerTemp** [comment]
Hi, this feature has been added in [3.1.4](https://github.com/TylerTemp/SaintsField/releases/tag/3.1.4) you can have a try.

**Comment by laurentopia** [comment]
Great, 
I just realized that I'm still in 3.0.14.
noob question: is there a way to update directly from the package manager?

**Comment by TylerTemp** [comment]
Depending on how you install the package:

1.  AssetStore: Yes. But it's 3-5 days delay for new version because Unity need to review it
2.  OpenUPM: run the command again: `openupm add today.comes.saintsfield`
3.  git upm: Yes. If it does not shown, edit `Packages/packages-lock.json` and delete:

    ```json
    "today.comes.saintsfield": {
      "version": "https://github.com/TylerTemp/SaintsField.git#dev",
      "depth": 0,
      "source": "git",
      "dependencies": {},
      "hash": "some hash string"
    },
    ```

4.  `unitypackage`: No, you need to download the new file and import it again'
5.  git submodule: `cd Assets/SaintsField`, then `git pull`
