### ISSUE TITLE
3.1.5 regression? GetComponentInChildren doesn't get component in self.

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#56]
It used to.
And GetComponentInChildren does that.
![image](https://github.com/user-attachments/assets/73a3dfb3-c5b2-4d44-907a-5a79c38dfa03)

**Comment by laurentopia** [comment]
![image](https://github.com/user-attachments/assets/da8a9af1-8358-4e40-b65f-6e627ad20c81)

**Comment by laurentopia** [comment]
and when I set a reference by hand it complains. 
![image](https://github.com/user-attachments/assets/2fd7b520-541c-4301-a512-2e06d18ac2d6)

**Comment by TylerTemp** [comment]
Hi,

By design `GetComponentInChildren` does not get component from self, this is different from Unity (so as GetComponentInParent(s))

However I am planing to change this behavior to align with Unity (in the next release) as it is confusing. Also because in previous version we can use `GetComponent` + `GetComponentInChildren`, but in last release they can no longer work together... So yeah it indeed needs to be changed.

**Comment by laurentopia** [comment]
Ok, good to know.

**Comment by laurentopia** [comment]
which is the latest version supporting _getcomponent + getcomponentinchildren_?

**Comment by TylerTemp** [comment]
3.1.3 does
3.1.4 GetComponent* start to support array, which break the `GetComponent` + `GetComponentInChildren`

**Comment by TylerTemp** [comment]
Hi @laurentopia ,

this behavior has been changed in [3.2.0](https://github.com/TylerTemp/SaintsField/releases/tag/3.2.0). This version has some breaking changes, please read the change log before upgrading.
