### ISSUE TITLE
UnassignedReferenceException with null-conditional

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#63]
Something I've never seen before:
`rigidBody?.AddForceAtPosition(direction, hitPoint, ForceMode.Impulse);`
causes that:
`UnassignedReferenceException: The variable rigidBody of MCUnit has not been assigned.`

and that's how rigidbody is set, automatically: 
![image](https://github.com/user-attachments/assets/e89f64b4-38b2-4679-8e23-d39e16ce62ac)

so either I never paid attention to that error before or GetComponent does something strange, other than nulling a field

**Comment by TylerTemp** [comment]
Hi,

this possible happens when things are correct in edit mode, and then when go to play mode, you manually active the object, and because in playing mode the logic is a bit different, this decorator might fail to get the component, and decide to null the field. (But not sure it's because of this)

I'll disable the `GetComponent*` ability in play mode in next release

**Comment by laurentopia** [comment]
I understand, it's probably better to do that so that it matches the behavior of a build.

**Comment by laurentopia** [comment]
It's a unity thing
unity object are some times kinda of but not really null :/
![image](https://github.com/user-attachments/assets/9f1ad773-f195-4e68-a3fd-2e32d99ee95b)
https://stackoverflow.com/questions/62678228/why-does-c-sharp-null-conditional-operator-not-work-with-unity-serializable-vari
