### ISSUE TITLE
IMGUI fancy foldout Layout

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#64]
foldout don't indent either
`[LayoutGroup("Damage", ELayout.Background | ELayout.Title | ELayout.FoldoutBox)]
`
![image](https://github.com/user-attachments/assets/553afd29-a525-467a-8275-a3794e26fa4c)

**Comment by TylerTemp** [comment]
Not supported yet.

But I'm not planning to do it either, cuz the best way is, maybe just change the outlook of foldout group in IMGUI, into the style of UI Toolkit, then most confusing will be gone.

But still, IMGUI is not a primary target for this project: the IMGUI support is only "it works in IMGUI".

So I'll put this feature much later

**Comment by TylerTemp** [comment]
Hi @laurentopia 

Please check [3.2.6](https://github.com/TylerTemp/SaintsField/releases/tag/3.2.6) which improved the `foldout` look in IMGUI, which looks completely different from the default foldout. Remember to use `FoldoutBox` instead of `Foldout`

```csharp
[Serializable]
public struct MyStruct
{
    public string myField;
}

public MyStruct foldoutAbove;

[Layout("Test", ELayout.FoldoutBox)] public string testBg;

public MyStruct foldoutBelow;
```

![image](https://github.com/user-attachments/assets/6cd7377e-3dfa-402c-8fb8-0164e671f809)

**Comment by laurentopia** [comment]
but do they nest? ;)

**Comment by TylerTemp** [comment]
> but do they nest? ;)

@laurentopia   See [comment on #65](https://github.com/TylerTemp/SaintsField/issues/65#issuecomment-2298957419)
