### ISSUE TITLE
there is a problem  Display CanvasGroup Component

### ISSUE THREAD

**Issue by ZeroUltra** [TylerTemp/SaintsField#7]
hi !!! It's me again.
In Unity2022.3.16
![image](https://github.com/TylerTemp/SaintsField/assets/38253805/8a35aaa7-e0d1-4ac7-b916-963ad0bb2709)
![image](https://github.com/TylerTemp/SaintsField/assets/38253805/2153cf03-7b00-48db-95f2-6d3237ebd542)
![image](https://github.com/TylerTemp/SaintsField/assets/38253805/c3bb5b18-efe6-47b2-a6e6-1bfcb48b630c)
![image](https://github.com/TylerTemp/SaintsField/assets/38253805/9a73b278-0e66-4316-a0dc-8dc9181cebd3)

***
I tried many times, and it all turned out like this.

then, Can describe SaintsEditor in more detail?

**Comment by TylerTemp** [comment]
Hi,

This is very weird... I also noticed that CanvasGroup inherited from `Behavior` rather than `MonoBehavior` or `Component` like most Unity components do (even though `Behavior` is inherited from `Component`)

I'm looking into it. Before it's fixed, here is a **temporary workaround**, to limit SaintsEditor on MonoBehavior & ScriptableObject only:

1.  Unapply `SaintsEditor`
2.  Create a folder named `Editor` anywhere under your `Assets`
3.  Create a "MyEditor.cs"(Or any name your like) and put:

```csharp
using SaintsField.Editor;

[CanEditMultipleObjects]
[CustomEditor(typeof(UnityEngine.MonoBehaviour), true)]
public class SaintsSimpleMonoEditor : SaintsEditor
{
}

[CanEditMultipleObjects]
[CustomEditor(typeof(UnityEngine.ScriptableObject), true)]
public class SaintsSimpleScriptableObjectEditor : SaintsEditor
{
}
```

**Comment by TylerTemp** [comment]
Please update to 2.1.13 to see if it's fixed.

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/5801f209-c728-4cbf-8b60-5a4edf1d6e99)

**Comment by ZeroUltra** [comment]
I tried it , fix the bug. In my country, we  said you 666(so good awesome...)
