### ISSUE TITLE
Rename "Apply SaintsEditor" to "Enable SaintsEditor"?

### ISSUE THREAD

**Issue by ModischFabrications** [TylerTemp/SaintsField#82]
Does "Apply SaintsEditor" mean "Enable SaintsEditor", and if so, why isn't it called that way? Unapply" is a similar case that could probably be "disable" instead. Not trying to be rude, but it seems that there is a deeper meaning that I haven't understood yet..? If so it might be sensible to extend the readme.

I'm not a native speaker, but I was skeptical to press the "Apply" Button because it sounds like it's going to apply non-reversible modifications. Is there a persistent change done to the project and/or editor? As far as I understand it's only a visual change.

Sidenote: You might want to move the explanation of SaintsEditor above the long list of possible attributes. I only found these instructions after wondering why the ".Playa" namespace didn't work.

**Comment by TylerTemp** [comment]
Sure :) thanks for the notice! Both suggestions sound good!

The first is because Unity's internal process makes it look like "apply" so I didn't think much.

The second is because, when the project gets started, the "Editor" level components was very not-important feature. As it grows, also as I'm using it heavily in my project, it now has become a big important part... BUT the description didn't receive it's importance as it should (embarrassingly but also politely smiley face insert here).

I'm still working on [some other features/issues](https://github.com/TylerTemp/SaintsField/milestone/6) so this will be processed later.
